#!/usr/bin/perl -w

use strict;
use warnings;
# Comment out next option before release!
#use diagnostics -verbose;

use Getopt::Long;
use Pod::Usage;
use Digest::SHA qw(sha1_hex);
use Exporter 'import';

use Lxc::object;

use Lxctl::helper;
use Lxctl::_config;


our $version = "0.2.000";

our $Lxc = Lxc::object->new;

sub help_me
{
	my $help = 0;
	my $man = 0;
	my $ver = 0;

	$Getopt::Long::passthrough = 1;
	GetOptions('help|?' => \$help, 'man' => \$man, 'version' => \$ver) or pod2usage(2);
	
	