#!/usr/bin/perl -w

use strict;
use warnings;
# Comment out next option before release!
#use diagnostics -verbose;

use Getopt::Long;
use Pod::Usage;
use Digest::SHA qw(sha1_hex);
use Exporter 'import';

use Lxc::object;

use Lxctl::helper;
use Lxctl::_config;


our $version = "0.1.900";

our $Lxc = Lxc::object->new;

sub help_me
{
	my $help = 0;
	my $man = 0;
	my $ver = 0;

	$Getopt::Long::passthrough = 1;
	GetOptions('help|?' => \$help, 'man' => \$man, 'version' => \$ver) or pod2usage(2);
	die "Version: $version\n" if $ver;
	if ($help) {
		pod2usage(1);
	} elsif ($man) {
		pod2usage(-exitstatus => 0, -verbose => 2);
	} elsif (@ARGV == 0) {
		pod2usage("No argument specified.");
	}
	$Lxc->check();
	$Getopt::Long::passthrough = 0;
}

sub lets_rock
{
	my $config = new Lxctl::_config;
	$config->load_main();

	help_me();

	my $action = shift @ARGV;
	my $class;
	my $helper = new Lxctl::helper;

	eval {
		$helper->load_module("Lxctl/$action.pm");
		$action = "Lxctl::$action";
		$action->import;
		$class = new $action;
	} or do {
		die "Unsupported command!\n\n$@\n\n";
	};

	$class->do(@ARGV);

	return;
}

lets_rock;

__END__

=head1 NAME

lxctl - Control various aspects of lxc.

=head1 SYNOPSIS

lxctl [action] [vmname] [options]

See lxctl --man or lxctl --help for more info

=head1 OPTIONS

=over 8

=item B<--help>

Print a breif help message and exists

=item B<--man>

Prints the manual page and exits.

=item B<start>

Starts container specified in 1st argument

B<Required arguments:>

	vmname - name of the container

=item B<stop>

Stops container specified in 1st argument

B<Required arguments:>

	vmname - name of the container

=item B<create>

Creates container.

B<Required arguments:>

	vmname - name of the container

	--ipaddr - IP address if the machine

	--netmask - network mask of the machine

	--defgw - default gateway of the machine

	--dns - primary DNS server

B<Optional arguments:>

	--ostemplate - template name, by default it is 'lucid_amd64'

	--config - path to configuration file, by default /etc/lxc/<container name> is used

	--root - path to root file system, by default /var/lxc/<container name> is used

	--pkgset - list of additional packages

	--rootsz - size of logical volume for root FS, by default it is 10G

	--hostname - sets the hostname of the machine, by default <container name> is used

=item B<set>

Changes container parameters.

B<Required arguments:>

	vmname - name of the container

B<Optional arguments:>

	--rootsz - increment of size of logical volume for root FS

	--ipaddr - IP address if the machine

	--netmask - network mask of the machine

	--defgw - default gateway of the machine

	--dns - primary DNS server

	--hostname - sets the hostname of the machine

	--userpasswd user:passwd - sets password for given user

	--onboot {yes,no} - makes containet [do not] start at boot

	--cpu - sets the CPU share of the container

	--mem - sets the memory share of the container (in bytes!)

	--io - sets the IO share of the container

=item B<freeze>

Freezes container

B<Required arguments:>

	vmname - name of the container

=item B<unfreeze>

Unfreezes container

B<Required arguments:>

	vmname - name of the container

=item B<list>

Lists all containers

B<Optional arguments:>

	--ipaddr - display with IP addr

	--hostname - display with hostname.
	
	--cgroup - display with cgroup

	--ipaddr - display with ip
		
	--mount - display with mount point for rootfs

	--diskspace - display with free/full size

	--all - display all information

	--raw - display only vmnames

=back

=head1 DESCRIPTION

B<lxctl> controls lxc :)

Man page by Capitan Obvious.

=head1 AUTHOR

Anatoly Burtsev, E<lt>anatolyburtsev@yandex.ruE<gt>
Pavel Potapenkov, E<lt>ppotapenkov@gmail.comE<gt>
Vladimir Smirnov, E<lt>civil.over@gmail.comE<gt>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2011 by Anatoly Burtsev, Pavel Potapenkov, Vladimir Smirnov

This script is free software; you can redistribute it and/or modify
it under the same terms of GPL v2 or later, or, at your opinion
under terms of artistic license.


=cut
